# Build settings

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:	     "David Hanraths"
description: "Digital portfolio for my projects in sonic arts and artistic research"
author:      "David Hanraths"

description: >- # this means to ignore newlines until "baseurl:"
    Documentation of DHanr's projects in music, artistic research and audio-electronics.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://functionaljerk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  "FunctionalJerk"
soundcloud_username: "d-the-dangerous"
bandcamp_username: "davidhanraths"

# Build settings
#port: 4000
markdown:  kramdown
permalink: pretty
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]


