#-------------------------------
# General Site Settings

menu:
#- {name: 'Home', url: ''}
- {name: 'Projects', url: 'projects'}
- {name: 'Media',    url: 'media'}
- {name: 'About',    url: 'about'}

#-------------------------------
# Projects Section

projects:
- {name: 'Apotrop',  url: 'Apotrop'}
- {name: 'DIY Granular-Synth',  url: 'Synth'}
- {name: 'EsKannNichtAllesBlumeSein', url: 'Blume'}
- {name: '°mm ↓m​:​°​,',   url: 'mm-m'}
- {name: 'tSNE-VocalSampler',   url: 'VocalSampler'}
- {name: 'Audio Data Mining', url: 'DataMining'}

#-------------------------------
# Contact Section

social:
#- {icon: 'mail',	link: 'mailto:d.hanraths(at)web.de'}
- {icon: 'github',	link: 'https://github.com/FunctionalJerk'}
- {icon: 'bandcamp',	link: 'https://davidhanraths.bandcamp.com'}
#- {icon: 'soundcloud',	link: 'https://soundcloud.com/d-the-dangerous'}

#-------------------------------
# SEO Section
# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Artist ortfolio by David Hanraths'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'


